### ISSUE TITLE
https://localhost/nextcloud doesn't work on MacOS (docker toolbox)

### ISSUE THREAD

**Issue by etournay** [greyltc/docker-nextcloud#2]
I would suggest something like `echo "https://$(docker-machine ip default)/nextcloud"` in the terminal. Then copy-paste the result onto a web browser. Then it works.
Is there a more elegant way ?
Best wishes,
Raphael

**Comment by greyltc** [comment]
So the readme instruction step number 3 isn't valid for MacOS (and probably windows too I assume). 

`docker-machine` is not a thing on my system. I see a few ways of opening a browser tab via a bash command, but I'm not so hopeful that those are super portable across platforms and I don't even know if we can assume we'll have bash in windows.

Here's a bash script that might do the job

``` bash
#!/bin/bash
HOST=localhost
SUBDIR=$1

if [ -x "$(command -v docker-machine)" ]
then
  HOST=$(docker-machine ip default)
fi

URL="https://$HOST/$SUBDIR"
[[ -x $BROWSER ]] && exec "$BROWSER" "$URL"
path=$(command -v xdg-open || command -v gnome-open) && exec "$path" "$URL"
echo "Can't find browser, manually browse to $URL"
```

Save that as browserOpen.sh and run it with `browserOpen.sh nextcloud`. Does it work in macOS?

This all kinda seems overly complicated. I don't know the best way to solve this aside from adding platform specific notes to the readme, but that doesn't seem so clean either.

**Comment by etournay** [comment]
Thanks a lot for the nice script. I modified it by adding `|| which open` to make it working on OSX.

``` bash
#!/bin/bash
HOST=localhost
SUBDIR=$1

if [ -x "$(command -v docker-machine)" ]
then
  HOST=$(docker-machine ip default)
fi

URL="https://$HOST/$SUBDIR"
#[[ -x $BROWSER ]] && exec "$BROWSER" "$URL"
path=$(which xdg-open || which gnome-open || which open) && exec "$path" "$URL"
echo "Can't find browser, manually browse to $URL"
```

FYI, when installing Docker on Windows and OSX, the intaller installs a toolbox including docker-machine and a QuickStart Terminal that is just a bash terminal (that you can use with Windows too). But I haven't tried the above script on Windows because I don't have Windows. Unlike Linux, on OSX and Win, Docker works using virtualization (maybe not true anymore for newer docker versions).

Best wishes,
Raphael

**Comment by greyltc** [comment]
Then the script should become

``` bash
#!/bin/bash
HOST=localhost
SUBDIR=$1

if [ -x "$(command -v docker-machine)" ]
then
  HOST=$(docker-machine ip default)
fi

URL="https://$HOST/$SUBDIR"
#[[ -x $BROWSER ]] && exec "$BROWSER" "$URL"
path=$(command -v xdg-open || command -v gnome-open || command -v open) && exec "$path" "$URL"
echo "Can't find your browser, manually browse to $URL"
```

How's that?

**Comment by greyltc** [comment]
I've added a note to the readme to cover Windows/MacOS. What do you think?

**Comment by etournay** [comment]
Yes, it works too. The note is great.

**Comment by greyltc** [comment]
Cool.
