### ISSUE TITLE
Cron isn't working

### ISSUE THREAD

**Issue by nrgeen** [greyltc/docker-nextcloud#3]
After moving from OwnCloud to Nextcloud the cron isn't working anymore.

**Comment by greyltc** [comment]
gah, I can't seem to keep that thing working!
I'll have a look at it...

**Comment by nrgeen** [comment]
Thanks!!!!! ;-)

**Comment by greyltc** [comment]
Are you 100% sure it's not working?

I see `Fatal    cron    Not installed` in the log (don't know why that's there)

I also see a green dot at `https://localhost/nextcloud/index.php/settings/admin#backgroundjobs` which tells me the last cron job went off 4 min ago.

I've verified that `php -f /var/www/owncloud/cron.php` is indeed being run every 15 minutes as it should be.

**Comment by nrgeen** [comment]
Yes, it's truly not working. :-(
Last cron job went off 9 hrs ago.

The cron.log say: 

```
Console has to be executed with the same user as the web server is operated
Current user: root
Web server user: http
```

Do you meen  `php -f /var/www/owncloud/cron.php` or `php -f /var/www/nextcloud/cron.php`?

Is there a way to check the state by terminal?

**Comment by greyltc** [comment]
Actually I mean `php -f /usr/share/webapps/nextcloud/cron.php`

**Comment by greyltc** [comment]
That's an unexpected error. I've got no idea why the cron job would be run as root. The [cron.conf I provide](https://github.com/greyltc/docker-nextcloud/blob/master/configs/cron.conf) runs the job as the http user. 

The vanilla image (following exactly the instructions in the readme) gives an image with a cron that seems to work.

Maybe some of your volume mappings are mapping over some things they should not be?

**Comment by nrgeen** [comment]
I had the same idea. 
Testing it at the moment.

**Comment by nrgeen** [comment]
Ok. I gave up and I restartet with my totally new nextcloud. ;-)

With the new container, the problem does not occur. The cron is working.
I hope that the problem does not come back.

Thanks for your support!

**Comment by nrgeen** [comment]
All back.
Also in my new configuration the cron stop working after installing the news app.
After that the cron isn't working anymore.

The cron.log says again:

```
Console has to be executed with the same user as the web server is operated
Current user: http
Web server user: 
```

Could the usermanagement have an problem?

On the other side probably the news-app needs an update....

**Comment by nrgeen** [comment]
The problem was in the file permissions of the mapped volumes. Could fix it after a long search. 

@greyltc Thanks for your patience and perseverance!

**Comment by greyltc** [comment]
I have a script built in that should fix up all the perms no matter how messed up they are:
run `set-nc-perms runtime` in the container.

**Comment by nrgeen** [comment]
Ah. Good to know for the next time.... ;-)
