### ISSUE TITLE
[Enhancement] Ability to select beta/RC Nextcloud versions

### ISSUE THREAD

**Issue by McBadass** [greyltc/docker-nextcloud#5]
It would be nice to be able to test the beta/RC versions in a container.  I did try this by changing the environment variable NC_VERSION to 10.0 but that didn't seem to make a difference.

**Comment by greyltc** [comment]
I'm not currently building any "tresting" or RC type releases (maybe I should be).
I do have an automated thing setup to build the daily releases (taken and built every day [from here](https://download.nextcloud.com/server/daily/latest.tar.bz2)). You can pull and run that by specifying the `:daily` tag like so

``` bash
docker pull greyltc/nextcloud:daily
docker run --name ncdaily -p 80:80 -p 443:443 -d greyltc/nextcloud:daily
```

You can see the status of my the daily builds [right here](https://hub.docker.com/r/greyltc/nextcloud/builds/).
Do you think that's good enough?

**Comment by McBadass** [comment]
The RC build I'm speaking to is on the 10x branch.  The daily builds are still on 9x.  I'm sure it won't normally be an issue since once they move to 10x it will probably be a while before they have another Beta/RC.  

Daily points to: https://download.nextcloud.com/server/daily/latest.tar.bz2 (version 9.0.52)
RC points to: https://download.nextcloud.com/server/prereleases/nextcloud-10.0RC1.tar.bz2

**Comment by greyltc** [comment]
Maybe the problem is that the nextcloud folks have their daily build release tarball pointing to an uninteresting branch?

**Comment by McBadass** [comment]
Somewhat related: 10.0 is now on the stable branch.  Neither docker-nextcloud daily or latest are pulling nextcloud 10.

**Comment by McBadass** [comment]
It looks like you did a build specifically for 10 so I'd say we can close this issue.
