### ISSUE TITLE
SSL Cert input

### ISSUE THREAD

**Issue by travis-r6s** [greyltc/docker-nextcloud#9]
Hi,

i copied the command  -v ~/sslCert:/root/sslKeys from the owncloud example, but although the container starts I cannot access it in the web browser? it just says
##############
This site can’t be reached

--.---.---.-- refused to connect.
Search Google for nextcloud
ERR_CONNECTION_REFUSED

#################

does that line work with this docker image?

thanks,

**Comment by McBadass** [comment]
What is the name of your certs?  What do you get when you run:

`docker logs nextcloud-docker-name`

**Comment by travis-r6s** [comment]
i have named them server.crt, and server.key as it says in the instructions i believe.
see below..

```
AH00526: Syntax error on line 143 of /etc/httpd/conf/extra/httpd-ssl.conf:
SSLCertificateFile: file '/root/sslKeys/fullchain.pem' does not exist or is empty
161129 07:24:01 mysqld_safe Logging to '/var/lib/mysql/2271a566029a.err'.
2016-11-29  7:24:02 140257078439424 [Note] /usr/bin/mysqld (mysqld 10.1.19-MariaDB) starting as process 133 ...
```

**Comment by McBadass** [comment]
Same thing happened to me.  You can rename/convert your server.crt and server.key to fullchain.pem and fullchain.key or you can change the apache config to server.crt and server.key (located at /etc/httpd/conf/extra/httpd-ssl.conf).  I would recommend that you rename your keys to match the default file at /etc/httpd/conf/extra/httpd-ssl.conf.  That way you don't thave to adjust the config file every time you pull a new docker image.

**Comment by travis-r6s** [comment]
okay, thanks. I will try that when i get a chance...

**Comment by greyltc** [comment]
You might have a look at the recently updated readme for my owncloud project: https://github.com/greyltc/docker-owncloud/blob/master/README.md
I rewrote method A there to be more accurate which should help you here.

**Comment by travis-r6s** [comment]
thanks, it works fine now. :)
however, would you be able to change the`sudo chmod 400 ~/sslCert/server.key` to `privkey.pem`?
